package com.labrinthmc.labrinth.world.room;

/** Room purposes plus size/height variants used by the procedural catalogue. */
public enum RoomKind {
    EMPTY,
    SMALL_STORAGE,
    LARGE_CHAMBER,
    UTILITY,
    CROSS_ROOM,
    LONG_RECTANGULAR,
    MULTI_EXIT,
    DEAD_END_REWARD,
    DECORATIVE,
    RARE_TEST,
    SMALL_CHAMBER,
    MEDIUM_CHAMBER,
    WIDE_CHAMBER,
    TALL_CHAMBER,
    GRAND_CHAMBER,
    SMALL_STORAGE_VARIANT,
    WIDE_GALLERY,
    TALL_ARCHIVE,
    CAVE_CHAMBER,
    GRAND_CAVE,
    JUNGLE_GROTTO,
    SPIDER_NEST,
    LARGE_SPIDER_NEST,
    WORKER_QUARTERS,
    OFFICER_QUARTERS,
    BARRACKS,
    STOCKADE,
    DINING_HALL,
    LIBRARY,
    GRAND_LIBRARY,
    TREASURY,
    FROZEN_CHAMBER,
    MASSIVE_HALL,
    CHAPEL,
    JAIL_BLOCK
}
